insert into login (username, name, password, roles) values ('makefile1', 'Makefile User 1', '1abc123456%$', ['role11', 'role12', 'role13']);
insert into login (username, name, password, roles) values ('makefile2', 'Makefile User 2', '2abc123456%$', ['role21', 'role22', 'role23']);
insert into login (username, name, password, roles) values ('makefile3', 'Makefile User 3', '3abc123456%$', ['role31', 'role32', 'role33']);
insert into login (username, name, password, roles) values ('makefile4', 'Makefile User 4', '4abc123456%$', ['role41', 'role42', 'role43']);
insert into login (username, name, password, roles) values ('makefile5', 'Makefile User 5', '5abc123456%$', ['role51', 'role52', 'role53']);
